apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wziciu8d0-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/wziciu8d0-dotnet-basic-gitops